package texasholdem.internal.testcommon

import texasholdem.internal.domain.Card
import texasholdem.internal.domain.Suits.{Clubs, Diamonds, Hearts, Spades}

trait TestCards {

  val C2: Card = Card(2, Clubs)
  val C3: Card = Card(3, Clubs)
  val C4: Card = Card(4, Clubs)
  val C5: Card = Card(5, Clubs)
  val C6: Card = Card(6, Clubs)
  val C7: Card = Card(7, Clubs)
  val C8: Card = Card(8, Clubs)
  val C9: Card = Card(9, Clubs)
  val CT: Card = Card(10, Clubs)
  val CJ: Card = Card(11, Clubs)
  val CQ: Card = Card(12, Clubs)
  val CK: Card = Card(13, Clubs)
  val CA: Card = Card(14, Clubs)

  val D2: Card = Card(2, Diamonds)
  val D3: Card = Card(3, Diamonds)
  val D4: Card = Card(4, Diamonds)
  val D5: Card = Card(5, Diamonds)
  val D6: Card = Card(6, Diamonds)
  val D7: Card = Card(7, Diamonds)
  val D8: Card = Card(8, Diamonds)
  val D9: Card = Card(9, Diamonds)
  val DT: Card = Card(10, Diamonds)
  val DJ: Card = Card(11, Diamonds)
  val DQ: Card = Card(12, Diamonds)
  val DK: Card = Card(13, Diamonds)
  val DA: Card = Card(14, Diamonds)

  val S2: Card = Card(2, Spades)
  val S3: Card = Card(3, Spades)
  val S4: Card = Card(4, Spades)
  val S5: Card = Card(5, Spades)
  val S6: Card = Card(6, Spades)
  val S7: Card = Card(7, Spades)
  val S8: Card = Card(8, Spades)
  val S9: Card = Card(9, Spades)
  val ST: Card = Card(10, Spades)
  val SJ: Card = Card(11, Spades)
  val SQ: Card = Card(12, Spades)
  val SK: Card = Card(13, Spades)
  val SA: Card = Card(14, Spades)

  val H2: Card = Card(2, Hearts)
  val H3: Card = Card(3, Hearts)
  val H4: Card = Card(4, Hearts)
  val H5: Card = Card(5, Hearts)
  val H6: Card = Card(6, Hearts)
  val H7: Card = Card(7, Hearts)
  val H8: Card = Card(8, Hearts)
  val H9: Card = Card(9, Hearts)
  val HT: Card = Card(10, Hearts)
  val HJ: Card = Card(11, Hearts)
  val HQ: Card = Card(12, Hearts)
  val HK: Card = Card(13, Hearts)
  val HA: Card = Card(14, Hearts)
}
